# Generated by Django 4.2.1 on 2023-05-13 07:37

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=django_bleach.models.BleachField(max_length=4096),
        ),
    ]
