# Generated by Django 4.2.1 on 2023-05-13 12:59

import comments.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_commentfile_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                default="username",
                max_length=254,
                verbose_name="Email address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(
                default="email@gmail.com",
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
                verbose_name="Username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commentfile",
            name="file",
            field=models.FileField(
                upload_to="comments/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ("jpg", "jpeg", "gif", "png", "txt")
                    ),
                    comments.validators.MaxDimensionsValidator(
                        max_height=240, max_width=320
                    ),
                    comments.validators.MaxFileSizeValidator(max_size=100),
                ],
            ),
        ),
    ]
